---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatekeeper-constraints
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./control-plane/common/gatekeeper/constraints
  prune: true
  dependsOn:
    - name: gatekeeper-constraint-templates
  sourceRef:
    kind: GitRepository
    name: control-plane

