---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatekeeper-constraints
  namespace: flux-system
spec:
  interval: 6h
  path: ./gatekeeper/constraints
  prune: true
  dependsOn:
    - name: gatekeeper-constraint-templates
  sourceRef:
    kind: GitRepository
    name: common

