---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gatekeeper/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: common
