---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatekeeper-constraint-templates
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./control-plane/common/gatekeeper/templates
  prune: true
  dependsOn:
    - name: gatekeeper
  sourceRef:
    kind: GitRepository
    name: control-plane

