apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workspace
  namespace: workspace-dev
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: workspace
