---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: workspace
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: workspace-dev
  url: https://github.com/makkes/flux-mc-control-plane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workspace
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: workspace
  dependsOn:
    - namespace: flux-system
      name: gatekeeper-constraints
