---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ca
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/cert-manager/ca
  prune: true
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-mc

