---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 6h
  path: ./control-plane/cert-manager/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: control-plane
  healthChecks:
    - kind: Deployment
      namespace: cert-manager
      name: cert-manager
    - kind: Deployment
      namespace: cert-manager
      name: cert-manager-cainjector
    - kind: Deployment
      namespace: cert-manager
      name: cert-manager-webhook
