---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: workspace
  namespace: workspace-staging
spec:
  interval: 1m0s
  ref:
    branch: workspace-staging
  url: https://github.com/makkes/flux-mc-control-plane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workspace
  namespace: workspace-staging
spec:
  interval: 6h
  prune: true
  serviceAccountName: staging
  sourceRef:
    kind: GitRepository
    name: workspace
