apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredServiceAccountName
metadata:
  name: helmrelease-must-have-sa
spec:
  match:
    kinds:
      - apiGroups: ["helm.toolkit.fluxcd.io"]
        kinds: ["HelmRelease"]
    excludedNamespaces: ["flux-system"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredServiceAccountName
metadata:
  name: kustomization-must-have-sa
spec:
  match:
    kinds:
      - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        kinds: ["Kustomization"]
    excludedNamespaces: ["flux-system"]
