---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-mc

